//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.42
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace DSLFactory.Candle.SystemModel.WSReferentiel
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using DSLFactory.Candle.SystemModel.Strategies;
    using DSLFactory.Candle.SystemModel.Repository;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Web.Services", "2.0.50727.42" )]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Web.Services.WebServiceBindingAttribute( Name="RepositoryStrategiesServiceSoap", Namespace="http://www.DSLFactory.org/Candle" )]
    public partial class RepositoryStrategiesService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        private System.Threading.SendOrPostCallback GetStrategyManifestsOperationCompleted;

        /// <remarks/>
        public RepositoryStrategiesService()
        {
        }
      
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.DSLFactory.org/Candle/GetStrategyManifests", RequestNamespace = "http://www.DSLFactory.org/Candle", ResponseNamespace = "http://www.DSLFactory.org/Candle", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StrategyManifest[] GetStrategyManifests()
        {
            object[] results = this.Invoke("GetStrategyManifests", new object[] {});
            return ( (StrategyManifest[])( results[0] ) );
        }

        /// <remarks/>
        public void GetStrategyManifestsAsync()
        {
            this.GetStrategyManifestsAsync(null);
        }

        /// <remarks/>
        public void GetStrategyManifestsAsync(object userState)
        {
            if ((this.GetStrategyManifestsOperationCompleted == null))
            {
                this.GetStrategyManifestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStrategyManifestsOperationCompleted);
            }
            this.InvokeAsync("GetStrategyManifests", new object[] {}, this.GetStrategyManifestsOperationCompleted, userState);
        }

        private void OnGetStrategyManifestsOperationCompleted(object arg)
        {

        }

        /// <remarks/>
        public new void CancelAsync( object userState )
        {
            base.CancelAsync( userState );
        }

        private bool IsLocalFileSystemWebService( string url )
        {
            if( ( ( url == null ) 
                        || ( url == string.Empty ) ) )
            {
                return false;
            }
            System.Uri wsUri = new System.Uri( url );
            if( ( ( wsUri.Port >= 1024 ) 
                        && ( string.Compare( wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase ) == 0 ) ) )
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Web.Services", "2.0.50727.42" )]
    public delegate void GetGetStrategyManifestsCompletedEventHandler(object sender, GetStrategyManifestsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Web.Services", "2.0.50727.42" )]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    public partial class GetStrategyManifestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetStrategyManifestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base( exception, cancelled, userState )
        {
            this.results = results;
        }

        /// <remarks/>
        public StrategyManifest[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ( (StrategyManifest[])( this.results[0] ) );
            }
        }
    }
}

#pragma warning restore 1591