 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace DSLFactory.Candle.SystemModel
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class ForeignKey
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Column == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						DSLFactory.Candle.SystemModel.CandleDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"ForeignKey", "", "Column"),
						"DSL0001", this);
			}
			if (this.PrimaryKey == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						DSLFactory.Candle.SystemModel.CandleDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"ForeignKey", "", "PrimaryKey"),
						"DSL0001", this);
			}
		} // ValidateMultiplicity
	} // class ForeignKey
} // DSLFactory.Candle.SystemModel

namespace DSLFactory.Candle.SystemModel
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class InterfaceLayer
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.LayerPackage == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						DSLFactory.Candle.SystemModel.CandleDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"InterfaceLayer", this.Name, "LayerPackage"),
						"DSL0001", this);
			}
		} // ValidateMultiplicity
	} // class InterfaceLayer
} // DSLFactory.Candle.SystemModel

	
 