//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace DSLFactory.Candle.SystemModel
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class CandleToolboxHelper : CandleToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new CandleToolboxHelper.
		/// </summary>
		public CandleToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	public abstract class CandleToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify Candle toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "Candle.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify Reference connector tool.
		/// </summary>
		public const string ReferenceFilterString = "Reference.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify Association connector tool.
		/// </summary>
		public const string AssociationFilterString = "Association.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify Generalization connector tool.
		/// </summary>
		public const string GeneralizationFilterString = "Generalization.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify Action connector tool.
		/// </summary>
		public const string ActionFilterString = "Action.1.0";

		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new CandleToolboxHelperBase.
		/// </summary>
		protected CandleToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::DSLFactory.Candle.SystemModel.CandleDomainModel.SingletonResourceManager.GetString("SystemModelToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 4;
			}
		}
		

		/// <summary>
		/// Returns a list of toolbox items for use with this DSL.
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			
			// Create store and load domain models.
			using(DslModeling::Store store = new DslModeling::Store(this.ServiceProvider))
			{
				store.LoadDomainModels(typeof(DslDiagrams::CoreDesignSurfaceDomainModel),
					typeof(global::DSLFactory.Candle.SystemModel.CandleDomainModel));
				global::System.Resources.ResourceManager resourceManager = global::DSLFactory.Candle.SystemModel.CandleDomainModel.SingletonResourceManager;
				global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			
				// Open transaction so we can create model elements corresponding to toolbox items.
				using(DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{

					// Add Implementation shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ImplementationToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ImplementationToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ImplementationToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"SystemModelToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("SystemModelToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ImplementationHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ImplementationToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.ClassImplementation.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add Reference connector tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ReferenceToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ReferenceToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ReferenceToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"SystemModelToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("SystemModelToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ReferenceHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ReferenceToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ReferenceFilterString)
						}));

					// Add Contract shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ContractToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ContractToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ContractToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"SystemModelToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("SystemModelToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Contract", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ContractToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.ServiceContract.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add Process shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ProcessToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ProcessToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ProcessToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"SystemModelToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("SystemModelToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Process", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ProcessToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.Process.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add PackageModel shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"PackageModelToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PackageModelToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PackageModelToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"ModelsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ModelsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PackageModelHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PackageModelToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.Package.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add EntityModel shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"EntityModelToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EntityModelToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EntityModelToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"ModelsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ModelsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"DefinedTypeHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EntityModelToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.Entity.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add EnumModel shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"EnumModelToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnumModelToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnumModelToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"ModelsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ModelsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnumModelHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnumModelToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.Enumeration.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add Association connector tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"AssociationToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AssociationToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AssociationToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"ModelsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ModelsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AssociationHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AssociationToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(AssociationFilterString)
						}));

					// Add Generalization connector tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"GeneralizationToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("GeneralizationToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("GeneralizationToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"ModelsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ModelsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Generalization", // F1 help keyword for the toolbox item.
						resourceManager.GetString("GeneralizationToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(GeneralizationFilterString)
						}));

					// Add Scenario shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ScenarioToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ScenarioToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ScenarioToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UILayerToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("UILayerToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ScenarioHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ScenarioToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.Scenario.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add UiView shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"UiViewToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("UiViewToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("UiViewToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UILayerToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("UILayerToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"UIViewId", // F1 help keyword for the toolbox item.
						resourceManager.GetString("UiViewToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.UIView.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add Action connector tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ActionToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ActionToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ActionToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UILayerToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("UILayerToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ActionHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ActionToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ActionFilterString)
						}));

					// Add Component shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ComponentToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ComponentToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ComponentToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ComponentHelpKeyword", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ComponentToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.SoftwareComponent.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add ExternalSoftwareComponent shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ExternalSoftwareComponentToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ExternalSoftwareComponentToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ExternalSoftwareComponentToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ExternalComponentHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ExternalSoftwareComponentToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.ExternalComponent.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add ExternalAssembly shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"ExternalAssemblyToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ExternalAssemblyToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ExternalAssemblyToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ExternalAssemblyHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ExternalAssemblyToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.DotNetAssembly.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add PresentationLayer shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"PresentationLayerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PresentationLayerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PresentationLayerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PresentationLayerHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PresentationLayerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.PresentationLayer.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add UIWorkflowLayer shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"UIWorkflowLayerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("UIWorkflowLayerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("UIWorkflowLayerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"UIWorkflowLayer", // F1 help keyword for the toolbox item.
						resourceManager.GetString("UIWorkflowLayerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.UIWorkflowLayer.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add BusinessLayer shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"BusinessLayerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("BusinessLayerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("BusinessLayerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"BusinessLayerHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("BusinessLayerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.BusinessLayer.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add DataAccessLayer shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"DataAccessLayerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("DataAccessLayerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("DataAccessLayerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"DALLayerHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("DataAccessLayerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.DataAccessLayer.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add DataLayerModel shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"DataLayerModelToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("DataLayerModelToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("DataLayerModelToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"DataLayerModelHelp", // F1 help keyword for the toolbox item.
						resourceManager.GetString("DataLayerModelToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.DataLayer.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add InterfaceLayer shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"InterfaceLayerToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("InterfaceLayerToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("InterfaceLayerToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"InterfaceLayer", // F1 help keyword for the toolbox item.
						resourceManager.GetString("InterfaceLayerToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.InterfaceLayer.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add Library shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"LibraryToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("LibraryToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("LibraryToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"LayersToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("LayersToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Library", // F1 help keyword for the toolbox item.
						resourceManager.GetString("LibraryToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DSLFactory.Candle.SystemModel.BinaryComponent.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					t.Rollback();
				}
			}

			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}
	}
}
