//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSLFactory.Candle.SystemModel
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "cml";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Candle";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"DSLFactory";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID CandleDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CandleCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID CandleExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CandleCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewCandleExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CandleCommandSetId), 0x0001);
	
		// Package identifier
		public const string CandlePackageId = "acd37819-aa0b-4ba5-a47b-ee768b93d93e";
		
		// Editor factory identifier
		public const string CandleEditorFactoryId = "a347c751-7722-4fa1-b73e-2e03db41d1c9";
		
		// Model explorer tool window identifier
		public const string CandleModelExplorerToolWindowId = "f6628fb0-4d5d-4071-a697-13afaa5a686b";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace DSLFactory.Candle.SystemModel
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string CandleCommandSetId = "47747347-8334-4049-ac3f-6164b9c7c8dd";
	}
}